### ISSUE TITLE
Feat: Child component trong dialog bị unmount mỗi lần đóng mở dialog

### ISSUE THREAD

**Issue by HieuPham2000** [HieuPham2000/DATN-frontend#28]
Dấu hiệu nhận biết: state bị reset
Cách check: 
`useEffect(() => {
        return () => console.log('HelperDialogContent unmount');
    }, []);`

**Comment by HieuPham2000** [comment]
https://github.com/mui/material-ui/issues/10572

**Comment by HieuPham2000** [comment]
Bổ sung keepMounted cho Dialog

**Comment by hero-oceansmart** [comment]
nếu có nhiều modal thì nó vẫn unmounted thôi em chai ^^
